version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: myapp-redis

    mysql:
      image: mysql:latest
      container_name: myapp-mysql
      working_dir: /myapp
      volumes:
        - .:/myapp
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=myapp
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=secret
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: myapp-webserver
      working_dir: /myapp
      volumes:
          - .:/myapp
          - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: Docker/php-fpm
      container_name: myapp-php-fpm
      working_dir: /myapp
      volumes:
        - .:/myapp
        - ./Docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

